# ==============================
#  Data Collection & Cleaning
# ==============================

## STEP 1 : Import & Load Data

In [58]:
import pandas as pd

df = pd.read_csv("retail_data_5000 - Copy.csv")

## STEP 2 : Checking Data Shape and Columns and data types

In [59]:
print(df.shape)      # rows and columns
print(df.columns)    # column names
print(df.info())     # data types + missing values

(5005, 9)
Index(['event_time', 'event type', 'product_id', 'category_id',
       'category_code', 'brand', 'price', 'user_id', 'user_session'],
      dtype='object')
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5005 entries, 0 to 5004
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   event_time     5005 non-null   object
 1   event type     5005 non-null   object
 2   product_id     4985 non-null   float64
 3   category_id    4996 non-null   float64
 4   category_code  3151 non-null   object
 5   brand          4088 non-null   object
 6   price          5000 non-null   float64
 7   user_id        4993 non-null   float64
 8   user_session   5001 non-null   object
dtypes: float64(4), object(5)
memory usage: 352.0+ KB
None

In [60]:
df.head()

,event_time,event type,product_id,category_id,category_code,brand,price,user_id,user_session
0,2019-11-01 00:06:51 UTC,view,1001588.0,2.050000e+18,electronics.smartphone,meizu,127.87,528269305.0,6dce75d2-e455-4e52-ab65-af16e36f64cb
1,2019-11-01 00:08:03 UTC,view,1002101.0,2.050000e+18,electronics.smartphone,samsung,370.64,540508491.0,33a0d8f4-c388-4ce7-85f4-7b1f11563d6a
2,2019-11-01 00:16:56 UTC,view,1002101.0,NaN,electronics.smartphone,samsung,370.64,NaN,8f65dac1-e176-4b72-b783-d9c5615ae858
3,2019-11-01 00:19:17 UTC,view,1002101.0,2.050000e+18,electronics.smartphone,samsung,370.64,565859861.0,e280986e-033c-4394-a0df-73354b42b80c
4,2019-11-01 00:27:56 UTC,view,1002101.0,2.050000e+18,electronics.smartphone,samsung,370.64,515031178.0,2cfd4fc1-3201-4c91-86ad-5d79a737c14d

In [61]:
df['category_id'] = df['category_id'].astype('Int64')
df['product_id'] = df['product_id'].astype('Int64')
df['user_id'] = df['user_id'].astype('Int64')

In [62]:
df.head()

,event_time,event type,product_id,category_id,category_code,brand,price,user_id,user_session
0,2019-11-01 00:06:51 UTC,view,1001588,2050000000000000000,electronics.smartphone,meizu,127.87,528269305,6dce75d2-e455-4e52-ab65-af16e36f64cb
1,2019-11-01 00:08:03 UTC,view,1002101,2050000000000000000,electronics.smartphone,samsung,370.64,540508491,33a0d8f4-c388-4ce7-85f4-7b1f11563d6a
2,2019-11-01 00:16:56 UTC,view,1002101,<NA>,electronics.smartphone,samsung,370.64,<NA>,8f65dac1-e176-4b72-b783-d9c5615ae858
3,2019-11-01 00:19:17 UTC,view,1002101,2050000000000000000,electronics.smartphone,samsung,370.64,565859861,e280986e-033c-4394-a0df-73354b42b80c
4,2019-11-01 00:27:56 UTC,view,1002101,2050000000000000000,electronics.smartphone,samsung,370.64,515031178,2cfd4fc1-3201-4c91-86ad-5d79a737c14d

## STEP 3 : Handiling Missing Values

In [66]:
df.columns

Index(['event_time', 'event type', 'product_id', 'category_id',
       'category_code', 'brand', 'price', 'user_id', 'user_session'],
      dtype='object')

In [67]:
print("Missing Values BEFORE cleaning:\n")
print(df.isnull().sum())

Missing Values BEFORE cleaning:

event_time          0
event type          0
product_id         20
category_id         9
category_code    1854
brand             917
price               5
user_id            12
user_session        4
dtype: int64

In [68]:
df = df.dropna(subset=['user_id'])

In [70]:
df.shape

(4993, 9)

In [71]:
#Numerical → Mean
#num_cols = df.select_dtypes(include=['int64','float64']).columns

#for col in num_cols:
    #df[col] = df[col].fillna(df[col].mean())
#df['price'] = df['price'].fillna(df['price'].mean())
#df.loc[(df['brand'] == 'Apple') & (df['price'].isna()), 'price'] = df.loc[df['brand'] == 'Apple', 'price'].mean()

C:\Users\Admin\AppData\Local\Temp\ipykernel_10348\395381415.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['price'] = df['price'].fillna(df['price'].mean())

In [72]:
df = df.copy()
df['price'] = df['price'].fillna(df['price'].mean())

In [73]:
# Categorical → Mode
cat_cols = df.select_dtypes(include=['object']).columns
#for col in cat_cols:
    #df[col] = df[col].fillna(df[col].mode()[0])

for col in df.select_dtypes(include='object').columns:
    df[col] = df[col].fillna(df[col].mode()[0])

In [74]:
print("Missing Values AFTER cleaning:\n")
print(df.isnull().sum())

Missing Values AFTER cleaning:

event_time        0
event type        0
product_id       19
category_id       6
category_code     0
brand             0
price             0
user_id           0
user_session      0
dtype: int64

In [77]:
print("Missing Values AFTER cleaning:\n")
print(df.isnull().sum())

Missing Values AFTER cleaning:

event_time       0
event type       0
product_id       0
category_id      0
category_code    0
brand            0
price            0
user_id          0
user_session     0
dtype: int64

In [76]:
df['category_id'] = df['category_id'].fillna(0)
df['product_id'] = df['product_id'].fillna(0)

##  Step 5 : Check Duplicates Rows

In [78]:
print("Duplicate Rows BEFORE:", df.duplicated().sum())

Duplicate Rows BEFORE: 5

In [79]:
df = df.drop_duplicates()

In [80]:
print("Duplicate Rows AFTER:", df.duplicated().sum())

Duplicate Rows AFTER: 0

## Step 6 : Check Inconsistent Text

In [83]:
print("Unique Country Values BEFORE:\n")
print(df['brand'].unique())
print(df['brand'].nunique())

Unique Country Values BEFORE:

['meizu' ' samsung' 'samsung' 'apple' 'xiaomi' 'huawei' 'nokia' 'APPLE'
 'oneplus' 'zte' 'sony' 'honor' 'lg' 'bq' 'Samsung' 'tp-link' 'oppo'
 'blackberry' 'vivo' 'htc' 'lenovo' 'acer' 'irbis' 'hp' 'dell' 'asus'
 'avalon' 'netechnics' 'neo' 'smart' 'pulser' 'xerox' 'epson' 'lexmark'
 'canon' 'philips' 'aoc' 'toshiba' 'haier' 'yasin' 'artel' 'hisense' 'tcl'
 'changhong' 'kivi' 'shivaki' 'horizont' 'ergo' 'blaupunkt' 'arg' 'nikon'
 'gopro' 'turbo' 'hansa' 'midea' 'electrolux' 'elenberg' 'gefest'
 'dauscher' 'flama' 'gorenje' 'bosch' 'atlant' 'pozis' 'indesit' 'beko'
 'whirlpool' 'hotpoint-ariston' 'vitek' 'redmond' 'moulinex' 'tefal'
 'polaris' 'candy' 'thomas' 'arnica' 'karcher' 'maxwell' 'braun' 'ariston'
 'aqua' 'oasis' 'timberk' 'scarlett' 'delonghi' 'smeg' 'neoline' 'anytek'
 'jbl' 'elari' 'harper' 'acme' 'usams' 'steelseries' 'janome' 'jaguar'
 'suunto' 'wonlex' 'aimoto' 'garmin' 'jet' 'ritmix' 'rowenta' 'remington'
 'saturn' 'babyliss' 'gemei' 'tv-shop' 'panasonic' 'pioneer' 'alpine'
 'telefunken' 'ams' 'infinity' 'hertz' 'avatar' 'nakamichi' 'phantom'
 'edge' 'kenwood' 'pride' 'alphard' 'element' 'prestigio' 'navitel'
 'starline' 'cenmax' 'tomahawk' 'pandora' 'ibox' 'intel' 'amd' 'gigabyte'
 'asrock' 'hyperx' 'palit' 'powercolor' 'msi' 'gainward' 'babyzen'
 'wingoffly' 'chicco' 'belecoo' 'babytime' 'mibb' 'lorelli' 'lego'
 'lorelli-bertoni' 'buderus' 'navien' 'riga' 'jinga' 'hiper' 'maxvi'
 'texet' 'inoi' 'disney' 'kingston' 'defender' 'brother' 'fly' 'aerocool'
 'thermaltake' 'byintek' 'llorens' 'silverlit' 'welly' 'bruder' 'bburago'
 'matrol' 'erbis' 'kitfort' 'hoco' 'svc' 'intro' 'sven' 'microlab'
 'samson' 'alesis' 'remax' 'caramelia' 'maomaoku' 'matrix' 'giant' 'scott'
 'cannondale' 'phoenix' 'author' 'cube' 'gt' 'axis' 'pinarello' 'dewalt'
 'kolner' 'hitachi' 'p.i.t.' 'crown' 'hyundai' 'alteco' 'matador'
 'yokohama' 'sava' 'triangle' 'cordiant' 'sailun' 'continental'
 'bridgestone' 'maxxis' 'bfgoodrich' 'nexen' 'viatti' 'nokian' 'michelin'
 'tigar' 'tunga' 'toyo' 'pirelli' 'goodyear' 'powertrac' 'habilead'
 'dunlop' 'hankook' 'roadstone' 'kormoran' 'comforser' 'roingto' 'nitto'
 'mazzini' 'kapsen' 'mirage' 'roadcruza' 'delmax' 'aoteli' 'roadx'
 'compasal' 'saferich' 'goodride' 'joyroad' 'maxtrek' 'x-game' 'skad'
 'alcasta' 'alutec' 'arrivo' 'kipardo' 'sv' 'brw' 'bts' 'stendmebel' 'kmk'
 'vegas' 'swisshome' 'sonel' 'askona' 'casper' 'cersanit' 'erlit'
 'colombo' 'rossinka' 'laufen' 'yamaha' 'cortland' 'kawai' 'rapid' 'axper'
 'permanence' 'pinskdrev' 'ostamebel' 'imperial' 'lider' 'helvetia'
 'varta' 'westa' 'bars' 'gigawatt' 'deta' 'hyper' 'w-star' 't-rex'
 'genesis' 'sheyk' 'voltman' 'intex' 'bestway' 'huter' 'denzel' 'magnetta'
 'rondell' 'inhouse' 'maestro' 'berghoff' 'gipfel' 'agness' 'vinzer'
 'omron' 'rivertoys' 'adil' 'domini' 'barneo' 'mamadoma' 'nika' 'zeta'
 'komfort-s' 'rals' 'silva' 'aero' 'nik' 'trussardi' 'montale' 'creed'
 'dior' 'lanvin' 'givenchy' 'chanel' 'lacoste' 'pupa' 'bourjois' 'eveline'
 'evelinecosmetics' 'nivea' 'iwalk' 'a-case' 'tarkett' 'rezult'
 'kronospan' 'eurolux' 'edon' 'nestogen' 'gerber' 'stiga' 'burton' 'ride'
 'sacvoyage' 'nike' 'casio' 'orient' 'armani' 'citizen' 'tissot'
 'longines' 'adriatica' 'swatch' 'naturehike' 'tuka' 'norfin' 'holiday'
 'outwell' 'mart' 'cablexpert' 'yato' 'total' 'aeroforce' 'force' 'stels'
 'stanley' 'startul' 'partner' 'shell' 'mobil' 'bardahl' 'gazpromneft'
 'toyota' 'motul' 'wenge' 'kirkland' 'preciosa' 'febest' 'machaon' 'sulu'
 'lucente' 'sokolov' 'trollbeads' 'merelani' 'hygge' 'genau' 'housefit'
 'ray-ban' 'tristar' 'kelli' 'romana' 'kartal' 'kovroff' 'karat' 'balta'
 'confetti' 'royal' 'picard' 'petek' 'baden' 'karya' 'spur' 'reebok'
 'asics' 'etor' 'greyder' 'respect' 'millionaire' 'catunltd' 'caprice'
 'adidas' 'strobbs' 'peak' 'puma' 'nexpero' 'rooman' 'fila' 'rieker'
 'fassen' 'burgerschuhe' 'tamaris' 'salamander' 'betsy' 'anta'
 'touchbeauty' 'gezatone' 'smile' 'bradex' 'masstone' 'bsn' 'beyond'
 'peda' 'doohan' 'racer' 'fubag' 'wert' 'forza' 'carver' 'deepcool'
 'humminbird' 'luminarc' 'onlitop' 'elysium' 'dam' 'prologic' 'fisherman'
 'leatherman' 'boyscout' 'hycell' 'energizer' 'cantra' 'carfashion'
 'milavitsa' 'obsessive' 'marmiton' 'vega' 'alpika' 'dion' 'jordan'
 'artmusical' 'garrett' 'fisher' 'pt-group' 'thule' 'broomer' 'solomon'
 'zubr' 't-max' 'goodloot' 'harley-davidson' 'dwt' 'hausmann'
 'biomecanics' 'pablosky' 'garvalin' 'dometic' 'coolfort' 'bresser'
 'akvaton' 'weekend' 'conceptclub' 'annaanna' 'hap-p-kid' 'rastar'
 'tomfarr' 'laston' 'perilla' 'gimi' 'ryobi' 'graphite' 'novline'
 'resanta']
481

In [86]:
df = df.copy()
# Remove spaces
df['brand'] = df['brand'].str.strip()

# Convert to lowercase
df['brand'] = df['brand'].str.lower()

In [87]:
print("Unique Country Values AFTER:\n")
print(df['brand'].unique())
print(df['brand'].nunique())

Unique Country Values AFTER:

['meizu' 'samsung' 'apple' 'xiaomi' 'huawei' 'nokia' 'oneplus' 'zte'
 'sony' 'honor' 'lg' 'bq' 'tp-link' 'oppo' 'blackberry' 'vivo' 'htc'
 'lenovo' 'acer' 'irbis' 'hp' 'dell' 'asus' 'avalon' 'netechnics' 'neo'
 'smart' 'pulser' 'xerox' 'epson' 'lexmark' 'canon' 'philips' 'aoc'
 'toshiba' 'haier' 'yasin' 'artel' 'hisense' 'tcl' 'changhong' 'kivi'
 'shivaki' 'horizont' 'ergo' 'blaupunkt' 'arg' 'nikon' 'gopro' 'turbo'
 'hansa' 'midea' 'electrolux' 'elenberg' 'gefest' 'dauscher' 'flama'
 'gorenje' 'bosch' 'atlant' 'pozis' 'indesit' 'beko' 'whirlpool'
 'hotpoint-ariston' 'vitek' 'redmond' 'moulinex' 'tefal' 'polaris' 'candy'
 'thomas' 'arnica' 'karcher' 'maxwell' 'braun' 'ariston' 'aqua' 'oasis'
 'timberk' 'scarlett' 'delonghi' 'smeg' 'neoline' 'anytek' 'jbl' 'elari'
 'harper' 'acme' 'usams' 'steelseries' 'janome' 'jaguar' 'suunto' 'wonlex'
 'aimoto' 'garmin' 'jet' 'ritmix' 'rowenta' 'remington' 'saturn'
 'babyliss' 'gemei' 'tv-shop' 'panasonic' 'pioneer' 'alpine' 'telefunken'
 'ams' 'infinity' 'hertz' 'avatar' 'nakamichi' 'phantom' 'edge' 'kenwood'
 'pride' 'alphard' 'element' 'prestigio' 'navitel' 'starline' 'cenmax'
 'tomahawk' 'pandora' 'ibox' 'intel' 'amd' 'gigabyte' 'asrock' 'hyperx'
 'palit' 'powercolor' 'msi' 'gainward' 'babyzen' 'wingoffly' 'chicco'
 'belecoo' 'babytime' 'mibb' 'lorelli' 'lego' 'lorelli-bertoni' 'buderus'
 'navien' 'riga' 'jinga' 'hiper' 'maxvi' 'texet' 'inoi' 'disney'
 'kingston' 'defender' 'brother' 'fly' 'aerocool' 'thermaltake' 'byintek'
 'llorens' 'silverlit' 'welly' 'bruder' 'bburago' 'matrol' 'erbis'
 'kitfort' 'hoco' 'svc' 'intro' 'sven' 'microlab' 'samson' 'alesis'
 'remax' 'caramelia' 'maomaoku' 'matrix' 'giant' 'scott' 'cannondale'
 'phoenix' 'author' 'cube' 'gt' 'axis' 'pinarello' 'dewalt' 'kolner'
 'hitachi' 'p.i.t.' 'crown' 'hyundai' 'alteco' 'matador' 'yokohama' 'sava'
 'triangle' 'cordiant' 'sailun' 'continental' 'bridgestone' 'maxxis'
 'bfgoodrich' 'nexen' 'viatti' 'nokian' 'michelin' 'tigar' 'tunga' 'toyo'
 'pirelli' 'goodyear' 'powertrac' 'habilead' 'dunlop' 'hankook'
 'roadstone' 'kormoran' 'comforser' 'roingto' 'nitto' 'mazzini' 'kapsen'
 'mirage' 'roadcruza' 'delmax' 'aoteli' 'roadx' 'compasal' 'saferich'
 'goodride' 'joyroad' 'maxtrek' 'x-game' 'skad' 'alcasta' 'alutec'
 'arrivo' 'kipardo' 'sv' 'brw' 'bts' 'stendmebel' 'kmk' 'vegas'
 'swisshome' 'sonel' 'askona' 'casper' 'cersanit' 'erlit' 'colombo'
 'rossinka' 'laufen' 'yamaha' 'cortland' 'kawai' 'rapid' 'axper'
 'permanence' 'pinskdrev' 'ostamebel' 'imperial' 'lider' 'helvetia'
 'varta' 'westa' 'bars' 'gigawatt' 'deta' 'hyper' 'w-star' 't-rex'
 'genesis' 'sheyk' 'voltman' 'intex' 'bestway' 'huter' 'denzel' 'magnetta'
 'rondell' 'inhouse' 'maestro' 'berghoff' 'gipfel' 'agness' 'vinzer'
 'omron' 'rivertoys' 'adil' 'domini' 'barneo' 'mamadoma' 'nika' 'zeta'
 'komfort-s' 'rals' 'silva' 'aero' 'nik' 'trussardi' 'montale' 'creed'
 'dior' 'lanvin' 'givenchy' 'chanel' 'lacoste' 'pupa' 'bourjois' 'eveline'
 'evelinecosmetics' 'nivea' 'iwalk' 'a-case' 'tarkett' 'rezult'
 'kronospan' 'eurolux' 'edon' 'nestogen' 'gerber' 'stiga' 'burton' 'ride'
 'sacvoyage' 'nike' 'casio' 'orient' 'armani' 'citizen' 'tissot'
 'longines' 'adriatica' 'swatch' 'naturehike' 'tuka' 'norfin' 'holiday'
 'outwell' 'mart' 'cablexpert' 'yato' 'total' 'aeroforce' 'force' 'stels'
 'stanley' 'startul' 'partner' 'shell' 'mobil' 'bardahl' 'gazpromneft'
 'toyota' 'motul' 'wenge' 'kirkland' 'preciosa' 'febest' 'machaon' 'sulu'
 'lucente' 'sokolov' 'trollbeads' 'merelani' 'hygge' 'genau' 'housefit'
 'ray-ban' 'tristar' 'kelli' 'romana' 'kartal' 'kovroff' 'karat' 'balta'
 'confetti' 'royal' 'picard' 'petek' 'baden' 'karya' 'spur' 'reebok'
 'asics' 'etor' 'greyder' 'respect' 'millionaire' 'catunltd' 'caprice'
 'adidas' 'strobbs' 'peak' 'puma' 'nexpero' 'rooman' 'fila' 'rieker'
 'fassen' 'burgerschuhe' 'tamaris' 'salamander' 'betsy' 'anta'
 'touchbeauty' 'gezatone' 'smile' 'bradex' 'masstone' 'bsn' 'beyond'
 'peda' 'doohan' 'racer' 'fubag' 'wert' 'forza' 'carver' 'deepcool'
 'humminbird' 'luminarc' 'onlitop' 'elysium' 'dam' 'prologic' 'fisherman'
 'leatherman' 'boyscout' 'hycell' 'energizer' 'cantra' 'carfashion'
 'milavitsa' 'obsessive' 'marmiton' 'vega' 'alpika' 'dion' 'jordan'
 'artmusical' 'garrett' 'fisher' 'pt-group' 'thule' 'broomer' 'solomon'
 'zubr' 't-max' 'goodloot' 'harley-davidson' 'dwt' 'hausmann'
 'biomecanics' 'pablosky' 'garvalin' 'dometic' 'coolfort' 'bresser'
 'akvaton' 'weekend' 'conceptclub' 'annaanna' 'hap-p-kid' 'rastar'
 'tomfarr' 'laston' 'perilla' 'gimi' 'ryobi' 'graphite' 'novline'
 'resanta']
478

In [88]:
df.head(5)

,event_time,event type,product_id,category_id,category_code,brand,price,user_id,user_session
0,2019-11-01 00:06:51 UTC,view,1001588,2050000000000000000,electronics.smartphone,meizu,127.87,528269305,6dce75d2-e455-4e52-ab65-af16e36f64cb
1,2019-11-01 00:08:03 UTC,view,1002101,2050000000000000000,electronics.smartphone,samsung,370.64,540508491,33a0d8f4-c388-4ce7-85f4-7b1f11563d6a
3,2019-11-01 00:19:17 UTC,view,1002101,2050000000000000000,electronics.smartphone,samsung,370.64,565859861,e280986e-033c-4394-a0df-73354b42b80c
4,2019-11-01 00:27:56 UTC,view,1002101,2050000000000000000,electronics.smartphone,samsung,370.64,515031178,2cfd4fc1-3201-4c91-86ad-5d79a737c14d
5,2019-11-01 00:22:25 UTC,view,1002482,2050000000000000000,electronics.smartphone,meizu,127.87,534887905,6a699abb-bdf8-43b7-86b7-bb89f6e8d4ed

In [89]:
df[df['price']<0]

,event_time,event type,product_id,category_id,category_code,brand,price,user_id,user_session
4643,2019-11-01 00:25:52 UTC,view,32401217,2050000000000000000,electronics.smartphone,samsung,-27.03,512483076,5e3606fe-e6ba-457e-973c-d56822d9584e
4818,2019-11-01 00:00:35 UTC,view,44300009,2100000000000000000,apparel.jeans,samsung,-50.45,545220871,f278cca0-e0f6-49a3-819a-d961998282d5

 ## Step 7 : Check Invalid Values

In [90]:
print("Negative Quantity Count:", (df['price'] < 0).sum())

Negative Quantity Count: 2

In [97]:
df['price'] = df['price'].abs()

In [98]:
print("Negative Price Count:", (df['price'] < 0).sum())

Negative Price Count: 0

 ## Step 8 : Convert Date format

In [93]:
df['event_time'] = pd.to_datetime(df['event_time'], errors='coerce')

In [94]:
print(df.columns)

Index(['event_time', 'event type', 'product_id', 'category_id',
       'category_code', 'brand', 'price', 'user_id', 'user_session'],
      dtype='object')

 ## Step 9: Standardize Column Names

In [95]:
df.columns = df.columns.str.lower().str.replace(" ", "_")
print(df.columns)

Index(['event_time', 'event_type', 'product_id', 'category_id',
       'category_code', 'brand', 'price', 'user_id', 'user_session'],
      dtype='object')

## Step 10 : Final Check

In [99]:
print("Final Shape:", df.shape)

print("\nFinal Info:\n")
print(df.info())

print("\nPreview:\n")
print(df.head())

Final Shape: (4986, 9)

Final Info:

<class 'pandas.core.frame.DataFrame'>
Index: 4986 entries, 0 to 4999
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   event_time     4986 non-null   datetime64[ns, UTC]
 1   event_type     4986 non-null   object
 2   product_id     4986 non-null   Int64
 3   category_id    4986 non-null   Int64
 4   category_code  4986 non-null   object
 5   brand          4986 non-null   object
 6   price          4986 non-null   float64
 7   user_id        4986 non-null   Int64
 8   user_session   4986 non-null   object
dtypes: Int64(3), datetime64[ns, UTC](1), float64(1), object(4)
memory usage: 404.1+ KB
None

Preview:

                 event_time event_type  product_id          category_id  \
0 2019-11-01 00:06:51+00:00       view     1001588  2050000000000000000
1 2019-11-01 00:08:03+00:00       view     1002101  2050000000000000000
3 2019-11-01 00:19:17+00:00       view     1002101  2050000000000000000
4 2019-11-01 00:27:56+00:00       view     1002101  2050000000000000000
5 2019-11-01 00:22:25+00:00       view     1002482  2050000000000000000

            category_code    brand   price    user_id  \
0  electronics.smartphone    meizu  127.87  528269305
1  electronics.smartphone  samsung  370.64  540508491
3  electronics.smartphone  samsung  370.64  565859861
4  electronics.smartphone  samsung  370.64  515031178
5  electronics.smartphone    meizu  127.87  534887905

                           user_session
0  6dce75d2-e455-4e52-ab65-af16e36f64cb
1  33a0d8f4-c388-4ce7-85f4-7b1f11563d6a
3  e280986e-033c-4394-a0df-73354b42b80c
4  2cfd4fc1-3201-4c91-86ad-5d79a737c14d
5  6a699abb-bdf8-43b7-86b7-bb89f6e8d4ed

## Step 11 : Save Cleaned Dataset

In [25]:
df.to_csv("cleaned_retail_dataset.csv", index=False)

print("✅ Cleaned dataset saved")

✅ Cleaned dataset saved