## Data Cleaning

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("retail_data.csv")

In [3]:
df.head()

,event_time,event type,product_id,category_id,category_code,brand,price,user_id,user_session
0,2019-11-01 00:06:51 UTC,view,1001588.0,2.050000e+18,electronics.smartphone,meizu,127.87,528269305.0,6dce75d2-e455-4e52-ab65-af16e36f64cb
1,2019-11-01 00:08:03 UTC,view,1002101.0,2.050000e+18,electronics.smartphone,samsung,370.64,540508491.0,33a0d8f4-c388-4ce7-85f4-7b1f11563d6a
2,2019-11-01 00:16:56 UTC,view,1002101.0,NaN,electronics.smartphone,samsung,370.64,NaN,8f65dac1-e176-4b72-b783-d9c5615ae858
3,2019-11-01 00:19:17 UTC,view,1002101.0,2.050000e+18,electronics.smartphone,samsung,370.64,565859861.0,e280986e-033c-4394-a0df-73354b42b80c
4,2019-11-01 00:27:56 UTC,view,1002101.0,2.050000e+18,electronics.smartphone,samsung,370.64,515031178.0,2cfd4fc1-3201-4c91-86ad-5d79a737c14d

### To check,data shape,columns and datatypes

In [58]:
df.shape

(5005, 9)

In [59]:
df.columns

Index(['event_time', 'event type', 'product_id', 'category_id',
       'category_code', 'brand', 'price', 'user_id', 'user_session'],
      dtype='object')

In [60]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5005 entries, 0 to 5004
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   event_time     5005 non-null   object
 1   event type     5005 non-null   object
 2   product_id     4985 non-null   float64
 3   category_id    4996 non-null   float64
 4   category_code  3151 non-null   object
 5   brand          4088 non-null   object
 6   price          5000 non-null   float64
 7   user_id        4993 non-null   float64
 8   user_session   5001 non-null   object
dtypes: float64(4), object(5)
memory usage: 352.0+ KB

In [61]:
df['product_id'] = df['product_id'].astype('Int64')

In [62]:
df.head()

,event_time,event type,product_id,category_id,category_code,brand,price,user_id,user_session
0,2019-11-01 00:06:51 UTC,view,1001588,2.050000e+18,electronics.smartphone,meizu,127.87,528269305.0,6dce75d2-e455-4e52-ab65-af16e36f64cb
1,2019-11-01 00:08:03 UTC,view,1002101,2.050000e+18,electronics.smartphone,samsung,370.64,540508491.0,33a0d8f4-c388-4ce7-85f4-7b1f11563d6a
2,2019-11-01 00:16:56 UTC,view,1002101,NaN,electronics.smartphone,samsung,370.64,NaN,8f65dac1-e176-4b72-b783-d9c5615ae858
3,2019-11-01 00:19:17 UTC,view,1002101,2.050000e+18,electronics.smartphone,samsung,370.64,565859861.0,e280986e-033c-4394-a0df-73354b42b80c
4,2019-11-01 00:27:56 UTC,view,1002101,2.050000e+18,electronics.smartphone,samsung,370.64,515031178.0,2cfd4fc1-3201-4c91-86ad-5d79a737c14d

In [63]:
df['category_id'] = df['category_id'].astype('Int64')

In [64]:
df['user_id'] = df['user_id'].astype('Int64')

In [65]:
df.head(2)

,event_time,event type,product_id,category_id,category_code,brand,price,user_id,user_session
0,2019-11-01 00:06:51 UTC,view,1001588,2050000000000000000,electronics.smartphone,meizu,127.87,528269305,6dce75d2-e455-4e52-ab65-af16e36f64cb
1,2019-11-01 00:08:03 UTC,view,1002101,2050000000000000000,electronics.smartphone,samsung,370.64,540508491,33a0d8f4-c388-4ce7-85f4-7b1f11563d6a

In [66]:
df.isnull().sum()   # checking for null values

event_time          0
event type          0
product_id         20
category_id         9
category_code    1854
brand             917
price               5
user_id            12
user_session        4
dtype: int64

In [67]:
df = df.dropna(subset=['user_id'])

In [68]:
df.shape

(4993, 9)

In [69]:
df.isnull().sum()

event_time          0
event type          0
product_id         19
category_id         6
category_code    1851
brand             915
price               5
user_id             0
user_session        4
dtype: int64

In [16]:
print(df.isnull().sum().sum())

2800

## Checking Duplicates rows

In [70]:

print(df.duplicated().sum())

5

In [71]:
 df = df.drop_duplicates()

In [72]:
print(df.duplicated().sum())

0

In [73]:
df.isnull().sum()

event_time          0
event type          0
product_id         19
category_id         6
category_code    1851
brand             915
price               5
user_id             0
user_session        4
dtype: int64

In [74]:
df = df.copy()
df['price'] = df['price'].fillna(df['price'].mean())

In [75]:
df.isnull().sum()

event_time          0
event type          0
product_id         19
category_id         6
category_code    1851
brand             915
price               0
user_id             0
user_session        4
dtype: int64

In [76]:
num_col = df.select_dtypes( include=['Int64','float64']).columns

In [77]:
num_col

Index(['product_id', 'category_id', 'price', 'user_id'], dtype='object')

In [78]:
cat_col = df.select_dtypes(include=['object']).columns

In [79]:
cat_col

Index(['event_time', 'event type', 'category_code', 'brand', 'user_session'], dtype='object')

In [80]:
for col in cat_col:
    df[col] = df[col].fillna(df[col].mode()[0])

In [81]:
df.isnull().sum()

event_time        0
event type        0
product_id       19
category_id       6
category_code     0
brand             0
price             0
user_id           0
user_session      0
dtype: int64

In [82]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4988 entries, 0 to 4999
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   event_time     4988 non-null   object
 1   event type     4988 non-null   object
 2   product_id     4969 non-null   Int64
 3   category_id    4982 non-null   Int64
 4   category_code  4988 non-null   object
 5   brand          4988 non-null   object
 6   price          4988 non-null   float64
 7   user_id        4988 non-null   Int64
 8   user_session   4988 non-null   object
dtypes: Int64(3), float64(1), object(5)
memory usage: 404.3+ KB

In [83]:
df['product_id'] = df['product_id'].fillna(0)

In [84]:
df['category_id'] = df['category_id'].fillna(0)

In [85]:
df.isnull().sum()

event_time       0
event type       0
product_id       0
category_id      0
category_code    0
brand            0
price            0
user_id          0
user_session     0
dtype: int64

In [86]:
df.head(2)

,event_time,event type,product_id,category_id,category_code,brand,price,user_id,user_session
0,2019-11-01 00:06:51 UTC,view,1001588,2050000000000000000,electronics.smartphone,meizu,127.87,528269305,6dce75d2-e455-4e52-ab65-af16e36f64cb
1,2019-11-01 00:08:03 UTC,view,1002101,2050000000000000000,electronics.smartphone,samsung,370.64,540508491,33a0d8f4-c388-4ce7-85f4-7b1f11563d6a

## Consistency Checking

In [90]:
df['brand'].unique()

array(['meizu', ' samsung', 'samsung', 'apple', 'xiaomi', 'huawei',
       'nokia', 'APPLE', 'oneplus', 'zte', 'sony', 'honor', 'lg', 'bq',
       'Samsung', 'tp-link', 'oppo', 'blackberry', 'vivo', 'htc',
       'lenovo', 'acer', 'irbis', 'hp', 'dell', 'asus', 'avalon',
       'netechnics', 'neo', 'smart', 'pulser', 'xerox', 'epson',
       'lexmark', 'canon', 'philips', 'aoc', 'toshiba', 'haier', 'yasin',
       'artel', 'hisense', 'tcl', 'changhong', 'kivi', 'shivaki',
       'horizont', 'ergo', 'blaupunkt', 'arg', 'nikon', 'gopro', 'turbo',
       'hansa', 'midea', 'electrolux', 'elenberg', 'gefest', 'dauscher',
       'flama', 'gorenje', 'bosch', 'atlant', 'pozis', 'indesit', 'beko',
       'whirlpool', 'hotpoint-ariston', 'vitek', 'redmond', 'moulinex',
       'tefal', 'polaris', 'candy', 'thomas', 'arnica', 'karcher',
       'maxwell', 'braun', 'ariston', 'aqua', 'oasis', 'timberk',
       'scarlett', 'delonghi', 'smeg', 'neoline', 'anytek', 'jbl',
       'elari', 'harper', 'acme', 'usams', 'steelseries', 'janome',
       'jaguar', 'suunto', 'wonlex', 'aimoto', 'garmin', 'jet', 'ritmix',
       'rowenta', 'remington', 'saturn', 'babyliss', 'gemei', 'tv-shop',
       'panasonic', 'pioneer', 'alpine', 'telefunken', 'ams', 'infinity',
       'hertz', 'avatar', 'nakamichi', 'phantom', 'edge', 'kenwood',
       'pride', 'alphard', 'element', 'prestigio', 'navitel', 'starline',
       'cenmax', 'tomahawk', 'pandora', 'ibox', 'intel', 'amd',
       'gigabyte', 'asrock', 'hyperx', 'palit', 'powercolor', 'msi',
       'gainward', 'babyzen', 'wingoffly', 'chicco', 'belecoo',
       'babytime', 'mibb', 'lorelli', 'lego', 'lorelli-bertoni',
       'buderus', 'navien', 'riga', 'jinga', 'hiper', 'maxvi', 'texet',
       'inoi', 'disney', 'kingston', 'defender', 'brother', 'fly',
       'aerocool', 'thermaltake', 'byintek', 'llorens', 'silverlit',
       'welly', 'bruder', 'bburago', 'matrol', 'erbis', 'kitfort', 'hoco',
       'svc', 'intro', 'sven', 'microlab', 'samson', 'alesis', 'remax',
       'caramelia', 'maomaoku', 'matrix', 'giant', 'scott', 'cannondale',
       'phoenix', 'author', 'cube', 'gt', 'axis', 'pinarello', 'dewalt',
       'kolner', 'hitachi', 'p.i.t.', 'crown', 'hyundai', 'alteco',
       'matador', 'yokohama', 'sava', 'triangle', 'cordiant', 'sailun',
       'continental', 'bridgestone', 'maxxis', 'bfgoodrich', 'nexen',
       'viatti', 'nokian', 'michelin', 'tigar', 'tunga', 'toyo',
       'pirelli', 'goodyear', 'powertrac', 'habilead', 'dunlop',
       'hankook', 'roadstone', 'kormoran', 'comforser', 'roingto',
       'nitto', 'mazzini', 'kapsen', 'mirage', 'roadcruza', 'delmax',
       'aoteli', 'roadx', 'compasal', 'saferich', 'goodride', 'joyroad',
       'maxtrek', 'x-game', 'skad', 'alcasta', 'alutec', 'arrivo',
       'kipardo', 'sv', 'brw', 'bts', 'stendmebel', 'kmk', 'vegas',
       'swisshome', 'sonel', 'askona', 'casper', 'cersanit', 'erlit',
       'colombo', 'rossinka', 'laufen', 'yamaha', 'cortland', 'kawai',
       'rapid', 'axper', 'permanence', 'pinskdrev', 'ostamebel',
       'imperial', 'lider', 'helvetia', 'varta', 'westa', 'bars',
       'gigawatt', 'deta', 'hyper', 'w-star', 't-rex', 'genesis', 'sheyk',
       'voltman', 'intex', 'bestway', 'huter', 'denzel', 'magnetta',
       'rondell', 'inhouse', 'maestro', 'berghoff', 'gipfel', 'agness',
       'vinzer', 'omron', 'rivertoys', 'adil', 'domini', 'barneo',
       'mamadoma', 'nika', 'zeta', 'komfort-s', 'rals', 'silva', 'aero',
       'nik', 'trussardi', 'montale', 'creed', 'dior', 'lanvin',
       'givenchy', 'chanel', 'lacoste', 'pupa', 'bourjois', 'eveline',
       'evelinecosmetics', 'nivea', 'iwalk', 'a-case', 'tarkett',
       'rezult', 'kronospan', 'eurolux', 'edon', 'nestogen', 'gerber',
       'stiga', 'burton', 'ride', 'sacvoyage', 'nike', 'casio', 'orient',
       'armani', 'citizen', 'tissot', 'longines', 'adriatica', 'swatch',
       'naturehike', 'tuka', 'norfin', 'holiday', 'outwell', 'mart',
       'cablexpert', 'yato', 'total', 'aeroforce', 'force', 'stels',
       'stanley', 'startul', 'partner', 'shell', 'mobil', 'bardahl',
       'gazpromneft', 'toyota', 'motul', 'wenge', 'kirkland', 'preciosa',
       'febest', 'machaon', 'sulu', 'lucente', 'sokolov', 'trollbeads',
       'merelani', 'hygge', 'genau', 'housefit', 'ray-ban', 'tristar',
       'kelli', 'romana', 'kartal', 'kovroff', 'karat', 'balta',
       'confetti', 'royal', 'picard', 'petek', 'baden', 'karya', 'spur',
       'reebok', 'asics', 'etor', 'greyder', 'respect', 'millionaire',
       'catunltd', 'caprice', 'adidas', 'strobbs', 'peak', 'puma',
       'nexpero', 'rooman', 'fila', 'rieker', 'fassen', 'burgerschuhe',
       'tamaris', 'salamander', 'betsy', 'anta', 'touchbeauty',
       'gezatone', 'smile', 'bradex', 'masstone', 'bsn', 'beyond', 'peda',
       'doohan', 'racer', 'fubag', 'wert', 'forza', 'carver', 'deepcool',
       'humminbird', 'luminarc', 'onlitop', 'elysium', 'dam', 'prologic',
       'fisherman', 'leatherman', 'boyscout', 'hycell', 'energizer',
       'cantra', 'carfashion', 'milavitsa', 'obsessive', 'marmiton',
       'vega', 'alpika', 'dion', 'jordan', 'artmusical', 'garrett',
       'fisher', 'pt-group', 'thule', 'broomer', 'solomon', 'zubr',
       't-max', 'goodloot', 'harley-davidson', 'dwt', 'hausmann',
       'biomecanics', 'pablosky', 'garvalin', 'dometic', 'coolfort',
       'bresser', 'akvaton', 'weekend', 'conceptclub', 'annaanna',
       'hap-p-kid', 'rastar', 'tomfarr', 'laston', 'perilla', 'gimi',
       'ryobi', 'graphite', 'novline', 'resanta'], dtype=object)

In [91]:
df['brand'].nunique()

481

In [92]:
df['brand'] = df['brand'].str.strip()

In [93]:
df['brand'] = df['brand'].str.lower()

In [94]:
df['brand'].unique()

array(['meizu', 'samsung', 'apple', 'xiaomi', 'huawei', 'nokia',
       'oneplus', 'zte', 'sony', 'honor', 'lg', 'bq', 'tp-link', 'oppo',
       'blackberry', 'vivo', 'htc', 'lenovo', 'acer', 'irbis', 'hp',
       'dell', 'asus', 'avalon', 'netechnics', 'neo', 'smart', 'pulser',
       'xerox', 'epson', 'lexmark', 'canon', 'philips', 'aoc', 'toshiba',
       'haier', 'yasin', 'artel', 'hisense', 'tcl', 'changhong', 'kivi',
       'shivaki', 'horizont', 'ergo', 'blaupunkt', 'arg', 'nikon',
       'gopro', 'turbo', 'hansa', 'midea', 'electrolux', 'elenberg',
       'gefest', 'dauscher', 'flama', 'gorenje', 'bosch', 'atlant',
       'pozis', 'indesit', 'beko', 'whirlpool', 'hotpoint-ariston',
       'vitek', 'redmond', 'moulinex', 'tefal', 'polaris', 'candy',
       'thomas', 'arnica', 'karcher', 'maxwell', 'braun', 'ariston',
       'aqua', 'oasis', 'timberk', 'scarlett', 'delonghi', 'smeg',
       'neoline', 'anytek', 'jbl', 'elari', 'harper', 'acme', 'usams',
       'steelseries', 'janome', 'jaguar', 'suunto', 'wonlex', 'aimoto',
       'garmin', 'jet', 'ritmix', 'rowenta', 'remington', 'saturn',
       'babyliss', 'gemei', 'tv-shop', 'panasonic', 'pioneer', 'alpine',
       'telefunken', 'ams', 'infinity', 'hertz', 'avatar', 'nakamichi',
       'phantom', 'edge', 'kenwood', 'pride', 'alphard', 'element',
       'prestigio', 'navitel', 'starline', 'cenmax', 'tomahawk',
       'pandora', 'ibox', 'intel', 'amd', 'gigabyte', 'asrock', 'hyperx',
       'palit', 'powercolor', 'msi', 'gainward', 'babyzen', 'wingoffly',
       'chicco', 'belecoo', 'babytime', 'mibb', 'lorelli', 'lego',
       'lorelli-bertoni', 'buderus', 'navien', 'riga', 'jinga', 'hiper',
       'maxvi', 'texet', 'inoi', 'disney', 'kingston', 'defender',
       'brother', 'fly', 'aerocool', 'thermaltake', 'byintek', 'llorens',
       'silverlit', 'welly', 'bruder', 'bburago', 'matrol', 'erbis',
       'kitfort', 'hoco', 'svc', 'intro', 'sven', 'microlab', 'samson',
       'alesis', 'remax', 'caramelia', 'maomaoku', 'matrix', 'giant',
       'scott', 'cannondale', 'phoenix', 'author', 'cube', 'gt', 'axis',
       'pinarello', 'dewalt', 'kolner', 'hitachi', 'p.i.t.', 'crown',
       'hyundai', 'alteco', 'matador', 'yokohama', 'sava', 'triangle',
       'cordiant', 'sailun', 'continental', 'bridgestone', 'maxxis',
       'bfgoodrich', 'nexen', 'viatti', 'nokian', 'michelin', 'tigar',
       'tunga', 'toyo', 'pirelli', 'goodyear', 'powertrac', 'habilead',
       'dunlop', 'hankook', 'roadstone', 'kormoran', 'comforser',
       'roingto', 'nitto', 'mazzini', 'kapsen', 'mirage', 'roadcruza',
       'delmax', 'aoteli', 'roadx', 'compasal', 'saferich', 'goodride',
       'joyroad', 'maxtrek', 'x-game', 'skad', 'alcasta', 'alutec',
       'arrivo', 'kipardo', 'sv', 'brw', 'bts', 'stendmebel', 'kmk',
       'vegas', 'swisshome', 'sonel', 'askona', 'casper', 'cersanit',
       'erlit', 'colombo', 'rossinka', 'laufen', 'yamaha', 'cortland',
       'kawai', 'rapid', 'axper', 'permanence', 'pinskdrev', 'ostamebel',
       'imperial', 'lider', 'helvetia', 'varta', 'westa', 'bars',
       'gigawatt', 'deta', 'hyper', 'w-star', 't-rex', 'genesis', 'sheyk',
       'voltman', 'intex', 'bestway', 'huter', 'denzel', 'magnetta',
       'rondell', 'inhouse', 'maestro', 'berghoff', 'gipfel', 'agness',
       'vinzer', 'omron', 'rivertoys', 'adil', 'domini', 'barneo',
       'mamadoma', 'nika', 'zeta', 'komfort-s', 'rals', 'silva', 'aero',
       'nik', 'trussardi', 'montale', 'creed', 'dior', 'lanvin',
       'givenchy', 'chanel', 'lacoste', 'pupa', 'bourjois', 'eveline',
       'evelinecosmetics', 'nivea', 'iwalk', 'a-case', 'tarkett',
       'rezult', 'kronospan', 'eurolux', 'edon', 'nestogen', 'gerber',
       'stiga', 'burton', 'ride', 'sacvoyage', 'nike', 'casio', 'orient',
       'armani', 'citizen', 'tissot', 'longines', 'adriatica', 'swatch',
       'naturehike', 'tuka', 'norfin', 'holiday', 'outwell', 'mart',
       'cablexpert', 'yato', 'total', 'aeroforce', 'force', 'stels',
       'stanley', 'startul', 'partner', 'shell', 'mobil', 'bardahl',
       'gazpromneft', 'toyota', 'motul', 'wenge', 'kirkland', 'preciosa',
       'febest', 'machaon', 'sulu', 'lucente', 'sokolov', 'trollbeads',
       'merelani', 'hygge', 'genau', 'housefit', 'ray-ban', 'tristar',
       'kelli', 'romana', 'kartal', 'kovroff', 'karat', 'balta',
       'confetti', 'royal', 'picard', 'petek', 'baden', 'karya', 'spur',
       'reebok', 'asics', 'etor', 'greyder', 'respect', 'millionaire',
       'catunltd', 'caprice', 'adidas', 'strobbs', 'peak', 'puma',
       'nexpero', 'rooman', 'fila', 'rieker', 'fassen', 'burgerschuhe',
       'tamaris', 'salamander', 'betsy', 'anta', 'touchbeauty',
       'gezatone', 'smile', 'bradex', 'masstone', 'bsn', 'beyond', 'peda',
       'doohan', 'racer', 'fubag', 'wert', 'forza', 'carver', 'deepcool',
       'humminbird', 'luminarc', 'onlitop', 'elysium', 'dam', 'prologic',
       'fisherman', 'leatherman', 'boyscout', 'hycell', 'energizer',
       'cantra', 'carfashion', 'milavitsa', 'obsessive', 'marmiton',
       'vega', 'alpika', 'dion', 'jordan', 'artmusical', 'garrett',
       'fisher', 'pt-group', 'thule', 'broomer', 'solomon', 'zubr',
       't-max', 'goodloot', 'harley-davidson', 'dwt', 'hausmann',
       'biomecanics', 'pablosky', 'garvalin', 'dometic', 'coolfort',
       'bresser', 'akvaton', 'weekend', 'conceptclub', 'annaanna',
       'hap-p-kid', 'rastar', 'tomfarr', 'laston', 'perilla', 'gimi',
       'ryobi', 'graphite', 'novline', 'resanta'], dtype=object)

In [95]:
df['brand'].nunique()

478

In [96]:
df.head(2)

,event_time,event type,product_id,category_id,category_code,brand,price,user_id,user_session
0,2019-11-01 00:06:51 UTC,view,1001588,2050000000000000000,electronics.smartphone,meizu,127.87,528269305,6dce75d2-e455-4e52-ab65-af16e36f64cb
1,2019-11-01 00:08:03 UTC,view,1002101,2050000000000000000,electronics.smartphone,samsung,370.64,540508491,33a0d8f4-c388-4ce7-85f4-7b1f11563d6a

In [98]:
df[df['price']<0]

,event_time,event type,product_id,category_id,category_code,brand,price,user_id,user_session
4643,2019-11-01 00:25:52 UTC,view,32401217,2050000000000000000,electronics.smartphone,samsung,-27.03,512483076,5e3606fe-e6ba-457e-973c-d56822d9584e
4818,2019-11-01 00:00:35 UTC,view,44300009,2100000000000000000,apparel.jeans,samsung,-50.45,545220871,f278cca0-e0f6-49a3-819a-d961998282d5

In [100]:
df['price'] = df['price'].abs()

In [101]:
df[df['price']<0]

Empty DataFrame
Columns: [event_time, event type, product_id, category_id, category_code, brand, price, user_id, user_session]
Index: []

#  Identify the type of each variable: Nominal, Ordinal, Discrete, Continuous

In [102]:
df.dtypes

event_time        object
event type        object
product_id         Int64
category_id        Int64
category_code     object
brand             object
price            float64
user_id            Int64
user_session      object
dtype: object

In [103]:
df.head(2)

,event_time,event type,product_id,category_id,category_code,brand,price,user_id,user_session
0,2019-11-01 00:06:51 UTC,view,1001588,2050000000000000000,electronics.smartphone,meizu,127.87,528269305,6dce75d2-e455-4e52-ab65-af16e36f64cb
1,2019-11-01 00:08:03 UTC,view,1002101,2050000000000000000,electronics.smartphone,samsung,370.64,540508491,33a0d8f4-c388-4ce7-85f4-7b1f11563d6a

 # What is the distribution of products based on product_id?

In [104]:
df['product_id'].sort_values()

3131           0
18             0
58             0
72             0
90             0
          ...
4995    60500001
4996    60500001
4998    60500002
4997    60500002
4999    60500002
Name: product_id, Length: 4988, dtype: Int64

In [106]:
df['brand'].sort_values().head(10)

3670    a-case
3669    a-case
3653    a-case
3668    a-case
1146      acer
1162      acer
1163      acer
1164      acer
1176      acer
1177      acer
Name: brand, dtype: object

# How many unique users are present in the dataset (user_id)?

In [107]:
df['user_id'].nunique()

1113

  # Are there any missing values in the dataset?

In [116]:
print(df.isnull().sum().sum())

2821

#  Are the event types valid (view, cart, purchase)?

In [4]:
df['event type'].unique()
yes

array(['view', 'purchase', 'cart'], dtype=object)

In [89]:
#total_cells = df.size
#missing_celss = df.isnull().sum().sum()
#non_missing_values = total_cells-missing_celss
#accuracy = (non_missing_values/total_cells )*100

In [88]:
#accuracy